// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Padelito.Infrastructure.Data;

#nullable disable

namespace Padelito.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PadelitoDbContext))]
    [Migration("20260712231612_CompleteDemoSeed")]
    partial class CompleteDemoSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Padelito.Domain.Entities.AvailableTurn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("CourtId", "StartTime", "EndTime")
                        .IsUnique();

                    b.ToTable("AvailableTurns", null, t =>
                        {
                            t.HasCheckConstraint("CK_AvailableTurns_EndTime", "[EndTime] > [StartTime]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 9001,
                            CourtId = 9001,
                            EndTime = new TimeOnly(11, 30, 0),
                            IsActive = true,
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = 9002,
                            CourtId = 9001,
                            EndTime = new TimeOnly(19, 30, 0),
                            IsActive = true,
                            StartTime = new TimeOnly(18, 0, 0)
                        },
                        new
                        {
                            Id = 9003,
                            CourtId = 9002,
                            EndTime = new TimeOnly(17, 30, 0),
                            IsActive = true,
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Id = 9004,
                            CourtId = 9002,
                            EndTime = new TimeOnly(21, 30, 0),
                            IsActive = true,
                            StartTime = new TimeOnly(20, 0, 0)
                        },
                        new
                        {
                            Id = 9005,
                            CourtId = 9003,
                            EndTime = new TimeOnly(20, 30, 0),
                            IsActive = true,
                            StartTime = new TimeOnly(19, 0, 0)
                        });
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 9001,
                            PersonId = 9001
                        },
                        new
                        {
                            Id = 9002,
                            PersonId = 9002
                        },
                        new
                        {
                            Id = 9003,
                            PersonId = 9003
                        },
                        new
                        {
                            Id = 9004,
                            PersonId = 9004
                        });
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Clubs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Buenos Aires",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@padelito.com",
                            IsActive = true,
                            Name = "Padelito",
                            Phone = "11-4000-0000"
                        });
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("CourtTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("HourPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("CourtTypeId");

                    b.HasIndex("ClubId", "Name")
                        .IsUnique();

                    b.ToTable("Courts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Courts_HourPrice", "[HourPrice] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 9001,
                            ClubId = 1,
                            CourtTypeId = 2,
                            HourPrice = 18000m,
                            IsActive = true,
                            Name = "Central Demo"
                        },
                        new
                        {
                            Id = 9002,
                            ClubId = 1,
                            CourtTypeId = 3,
                            HourPrice = 22000m,
                            IsActive = true,
                            Name = "Norte Demo"
                        },
                        new
                        {
                            Id = 9003,
                            ClubId = 1,
                            CourtTypeId = 4,
                            HourPrice = 26000m,
                            IsActive = true,
                            Name = "Arena Demo"
                        });
                });

            modelBuilder.Entity("Padelito.Domain.Entities.CourtType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("CourtTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Concrete"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Synthetic Turf"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Indoor"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Premium"
                        });
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClubId = 1,
                            PersonId = 1
                        });
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount", "[Amount] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 9001,
                            Amount = 22950m,
                            Note = "Payment completo demo",
                            PaymentDate = new DateTime(2026, 7, 9, 11, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethodId = 4,
                            ReservationId = 9001
                        },
                        new
                        {
                            Id = 9002,
                            Amount = 15000m,
                            Note = "Seña en efectivo",
                            PaymentDate = new DateTime(2026, 7, 9, 13, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethodId = 1,
                            ReservationId = 9002
                        },
                        new
                        {
                            Id = 9003,
                            Amount = 27000m,
                            Note = "Venmo",
                            PaymentDate = new DateTime(2026, 7, 11, 15, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethodId = 5,
                            ReservationId = 9003
                        });
                });

            modelBuilder.Entity("Padelito.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("PaymentMethods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cash"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Debit Card"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Credit Card"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Bank Transfer"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Venmo"
                        });
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dni")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique()
                        .HasFilter("[Dni] IS NOT NULL");

                    b.ToTable("People", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Dni = "30111222",
                            Email = "carlos.benitez@padelito.com",
                            FirstName = "Carlos",
                            IsActive = true,
                            LastName = "Benitez",
                            Phone = "11-4000-1001"
                        },
                        new
                        {
                            Id = 9001,
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Dni = "35421678",
                            Email = "lucia.fernandez@example.com",
                            FirstName = "Lucía",
                            IsActive = true,
                            LastName = "Fernández",
                            Phone = "11-5821-4076"
                        },
                        new
                        {
                            Id = 9002,
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Dni = "32987412",
                            Email = "martin.sosa@example.com",
                            FirstName = "Martín",
                            IsActive = true,
                            LastName = "Sosa",
                            Phone = "11-4962-1180"
                        },
                        new
                        {
                            Id = 9003,
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Dni = "38741209",
                            Email = "valentina.rios@example.com",
                            FirstName = "Valentina",
                            IsActive = true,
                            LastName = "Ríos",
                            Phone = "11-6234-9041"
                        },
                        new
                        {
                            Id = 9004,
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Dni = "36109874",
                            Email = "nicolas.acosta@example.com",
                            FirstName = "Nicolás",
                            IsActive = true,
                            LastName = "Acosta",
                            Phone = "11-4487-6620"
                        });
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Promotions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Promotions_DateRange", "[DateTo] >= [DateFrom]");

                            t.HasCheckConstraint("CK_Promotions_DiscountPercentage", "[DiscountPercentage] >= 0 AND [DiscountPercentage] <= 100");
                        });

                    b.HasData(
                        new
                        {
                            Id = 9001,
                            DateFrom = new DateOnly(2026, 7, 1),
                            DateTo = new DateOnly(2026, 12, 31),
                            Description = "Beneficio demo para time slots seleccionados.",
                            DiscountPercentage = 15m,
                            IsActive = true,
                            Name = "Horario tranquilo demo"
                        });
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableTurnId")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReservationDate")
                        .HasColumnType("date");

                    b.Property<int>("ReservationStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AvailableTurnId");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("ReservationStatusId");

                    b.HasIndex("ReservationDate", "AvailableTurnId")
                        .IsUnique()
                        .HasFilter("[ReservationStatusId] <> 3");

                    b.ToTable("Reservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reservations_BasePrice", "[BasePrice] >= 0");

                            t.HasCheckConstraint("CK_Reservations_FinalPrice", "[FinalPrice] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 9001,
                            AvailableTurnId = 9001,
                            BasePrice = 27000m,
                            ClientId = 9001,
                            CreatedAt = new DateTime(2026, 7, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            FinalPrice = 22950m,
                            PromotionId = 9001,
                            ReservationDate = new DateOnly(2026, 7, 8),
                            ReservationStatusId = 4
                        },
                        new
                        {
                            Id = 9002,
                            AvailableTurnId = 9003,
                            BasePrice = 33000m,
                            ClientId = 9002,
                            CreatedAt = new DateTime(2026, 7, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            FinalPrice = 33000m,
                            ReservationDate = new DateOnly(2026, 7, 9),
                            ReservationStatusId = 4
                        },
                        new
                        {
                            Id = 9003,
                            AvailableTurnId = 9002,
                            BasePrice = 27000m,
                            ClientId = 9003,
                            CreatedAt = new DateTime(2026, 7, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            FinalPrice = 27000m,
                            ReservationDate = new DateOnly(2026, 7, 12),
                            ReservationStatusId = 2
                        },
                        new
                        {
                            Id = 9004,
                            AvailableTurnId = 9004,
                            BasePrice = 33000m,
                            ClientId = 9004,
                            CreatedAt = new DateTime(2026, 7, 11, 16, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            FinalPrice = 28050m,
                            PromotionId = 9001,
                            ReservationDate = new DateOnly(2026, 7, 13),
                            ReservationStatusId = 1
                        },
                        new
                        {
                            Id = 9005,
                            AvailableTurnId = 9005,
                            BasePrice = 39000m,
                            ClientId = 9001,
                            CreatedAt = new DateTime(2026, 7, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            FinalPrice = 39000m,
                            ReservationDate = new DateOnly(2026, 7, 10),
                            ReservationStatusId = 3
                        });
                });

            modelBuilder.Entity("Padelito.Domain.Entities.ReservationAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservationAudits", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 9001,
                            Action = "Created",
                            CreatedAt = new DateTime(2026, 7, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reservation demo creada para Lucía Fernández en court Central Demo.",
                            ReservationId = 9001,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 9002,
                            Action = "StatusChanged",
                            CreatedAt = new DateTime(2026, 7, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Status cambiado de Confirmed a Completed.",
                            ReservationId = 9001,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 9003,
                            Action = "Created",
                            CreatedAt = new DateTime(2026, 7, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reservation demo creada para Martín Sosa en court Norte Demo.",
                            ReservationId = 9002,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 9004,
                            Action = "Created",
                            CreatedAt = new DateTime(2026, 7, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reservation demo creada para Valentina Ríos en court Central Demo.",
                            ReservationId = 9003,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 9005,
                            Action = "Created",
                            CreatedAt = new DateTime(2026, 7, 11, 16, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reservation demo creada para Nicolás Acosta en court Norte Demo.",
                            ReservationId = 9004,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 9006,
                            Action = "Created",
                            CreatedAt = new DateTime(2026, 7, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reservation demo creada para Lucía Fernández en court Arena Demo.",
                            ReservationId = 9005,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 9007,
                            Action = "StatusChanged",
                            CreatedAt = new DateTime(2026, 7, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Status cambiado de Pending a Canceled.",
                            ReservationId = 9005,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Padelito.Domain.Entities.ReservationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ReservationStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Confirmed"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Canceled"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Reception"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Staff"
                        });
                });

            modelBuilder.Entity("Padelito.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAED2SFjyZfFosfjAmmH1n5FHdE59w+9e6K96p468HR/FvY6jo4v94M+pMCLf/9mpNhA==",
                            RoleId = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Padelito.Domain.Entities.AvailableTurn", b =>
                {
                    b.HasOne("Padelito.Domain.Entities.Court", "Court")
                        .WithMany("AvailableTurns")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Court");
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Client", b =>
                {
                    b.HasOne("Padelito.Domain.Entities.Person", "Person")
                        .WithOne("Client")
                        .HasForeignKey("Padelito.Domain.Entities.Client", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Court", b =>
                {
                    b.HasOne("Padelito.Domain.Entities.Club", "Club")
                        .WithMany("Courts")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelito.Domain.Entities.CourtType", "CourtType")
                        .WithMany("Courts")
                        .HasForeignKey("CourtTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("CourtType");
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Employee", b =>
                {
                    b.HasOne("Padelito.Domain.Entities.Club", "Club")
                        .WithMany("Employees")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelito.Domain.Entities.Person", "Person")
                        .WithOne("Employee")
                        .HasForeignKey("Padelito.Domain.Entities.Employee", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Padelito.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelito.Domain.Entities.Reservation", "Reservation")
                        .WithMany("Payments")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentMethod");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Padelito.Domain.Entities.AvailableTurn", "AvailableTurn")
                        .WithMany("Reservations")
                        .HasForeignKey("AvailableTurnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelito.Domain.Entities.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelito.Domain.Entities.Employee", "Employee")
                        .WithMany("Reservations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelito.Domain.Entities.Promotion", "Promotion")
                        .WithMany("Reservations")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Padelito.Domain.Entities.ReservationStatus", "ReservationStatus")
                        .WithMany("Reservations")
                        .HasForeignKey("ReservationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AvailableTurn");

                    b.Navigation("Client");

                    b.Navigation("Employee");

                    b.Navigation("Promotion");

                    b.Navigation("ReservationStatus");
                });

            modelBuilder.Entity("Padelito.Domain.Entities.ReservationAudit", b =>
                {
                    b.HasOne("Padelito.Domain.Entities.Reservation", "Reservation")
                        .WithMany("Audits")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Padelito.Domain.Entities.User", b =>
                {
                    b.HasOne("Padelito.Domain.Entities.Employee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("Padelito.Domain.Entities.User", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelito.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Padelito.Domain.Entities.AvailableTurn", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Client", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Club", b =>
                {
                    b.Navigation("Courts");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Court", b =>
                {
                    b.Navigation("AvailableTurns");
                });

            modelBuilder.Entity("Padelito.Domain.Entities.CourtType", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Padelito.Domain.Entities.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Person", b =>
                {
                    b.Navigation("Client");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Promotion", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Padelito.Domain.Entities.ReservationStatus", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Padelito.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
